<?php

namespace AniGrenoble\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    public function getPhotos(){
		$qb = $this->createQueryBuilder('i');

	    $qb->where($qb->expr()->isNotNull('i.categorie'));

	  	return $qb
	    	->getQuery()
	    	->getResult();
	}
}
