ani_grenoble_admin_homepage:
    path:     /
    defaults: { _controller: AniGrenobleAppBundle:Default:index }

sd6_production_admin_annonce:
    resource: "@AniGrenobleAdminBundle/Resources/config/routing/annonce.yml"
    prefix:   /admin/annonce

sd6_production_admin_image:
    resource: "@AniGrenobleAdminBundle/Resources/config/routing/image.yml"
    prefix:   /admin/image
